name: Python Test

on:
  workflow_call:
    inputs:
      caller:
        required: true
        type: string
      runs_on:
        required: false
        default: ubuntu-latest
        type: string
      python_version:
        required: false
        default: 3.11
        type: string
      branch_name:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runs_on }}
    if: contains(inputs.branch_name, 'feature')

    steps:
      - name: Welcome
        run: |
          echo Hello $CALLER ! Running PyTest
        env: 
          CALLER: ${{ inputs.caller }}
      - name: 'Checkout Repository'
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Check formatting with Black
        uses: psf/black@stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest -vv > pytest-results.txt

      - uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ inputs.python_version }}
          path: pytest-results.txt